platform :ios, '8.0'

target 'PopTip Demo' do
  use_frameworks!
  pod 'AMPopTip', path: '../'

  target 'PopTip DemoTests' do
    inherit! :search_paths
  end

  target 'PopTip DemoUITests' do
    inherit! :search_paths
  end

end
