source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target "PopTipDemo" do
    pod 'AMPopTip', path: '../'
end

target "PopTipDemoTests" do
    pod 'Specta', '1.0.5'
    pod 'Expecta', '1.0.5'
    pod 'Expecta+Snapshots', '2.0.0'
    pod 'OCMock', '3.2'
end

inhibit_all_warnings!
